version: "3"
services:
  proxy:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
     - "$PWD/proxy:/etc/nginx/conf.d:ro"
    environment:
      TZ: "Asia/Seoul"
    restart: always

  proxy-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - "$PWD/proxy:/etc/nginx/conf.d:rw"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "$PWD/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    environment:
      TZ: "Asia/Seoul"
    restart: always

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/mysql_data:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: "system"
      TZ: "Asia/Seoul"
    restart: always